///|
pub const Ai21 = "AI21"

///|
pub const AionLabs = "AionLabs"

///|
pub const Alibaba = "Alibaba"

///|
pub const AmazonBedrock = "Amazon Bedrock"

///|
pub const AmazonNova = "Amazon Nova"

///|
pub const Anthropic = "Anthropic"

///|
pub const ArceeAI = "Arcee AI"

///|
pub const AtlasCloud = "AtlasCloud"

///|
pub const Avian = "Avian"

///|
pub const Azure = "Azure"

///|
pub const BaseTen = "BaseTen"

///|
pub const BytePlus = "BytePlus"

///|
pub const BlackForestLabs = "Black Forest Labs"

///|
pub const Cerebras = "Cerebras"

///|
pub const Chutes = "Chutes"

///|
pub const Cirrascale = "Cirrascale"

///|
pub const Clarifai = "Clarifai"

///|
pub const Cloudflare = "Cloudflare"

///|
pub const Cohere = "Cohere"

///|
pub const Crusoe = "Crusoe"

///|
pub const DeepInfra = "DeepInfra"

///|
pub const DeepSeek = "DeepSeek"

///|
pub const Featherless = "Featherless"

///|
pub const Fireworks = "Fireworks"

///|
pub const Friendli = "Friendli"

///|
pub const GMICloud = "GMICloud"

///|
pub const GoPomelo = "GoPomelo"

///|
pub const Google = "Google"

///|
pub const GoogleAIStudio = "Google AI Studio"

///|
pub const Groq = "Groq"

///|
pub const Hyperbolic = "Hyperbolic"

///|
pub const Inception = "Inception"

///|
pub const InferenceNet = "InferenceNet"

///|
pub const Infermatic = "Infermatic"

///|
pub const Inflection = "Inflection"

///|
pub const Liquid = "Liquid"

///|
pub const Mara = "Mara"

///|
pub const Mancer2 = "Mancer 2"

///|
pub const Minimax = "Minimax"

///|
pub const ModelRun = "ModelRun"

///|
pub const Mistral = "Mistral"

///|
pub const Modular = "Modular"

///|
pub const MoonshotAI = "Moonshot AI"

///|
pub const Morph = "Morph"

///|
pub const NCompass = "NCompass"

///|
pub const Nebius = "Nebius"

///|
pub const NextBit = "NextBit"

///|
pub const Novita = "Novita"

///|
pub const Nvidia = "Nvidia"

///|
pub const OpenAI = "OpenAI"

///|
pub const OpenInference = "OpenInference"

///|
pub const Parasail = "Parasail"

///|
pub const Perplexity = "Perplexity"

///|
pub const Phala = "Phala"

///|
pub const Relace = "Relace"

///|
pub const SambaNova = "SambaNova"

///|
pub const SiliconFlow = "SiliconFlow"

///|
pub const Sourceful = "Sourceful"

///|
pub const Stealth = "Stealth"

///|
pub const StreamLake = "StreamLake"

///|
pub const Switchpoint = "Switchpoint"

///|
pub const Targon = "Targon"

///|
pub const Together = "Together"

///|
pub const Venice = "Venice"

///|
pub const WandB = "WandB"

///|
pub const Xiaomi = "Xiaomi"

///|
pub const XAI = "xAI"

///|
pub const ZAi = "Z.AI"

///|
pub const FakeProvider = "FakeProvider"
