"""Embed system skills into MoonBit assets.

Usage:
    python scripts/embed-skills.py
"""

from pathlib import Path
from hashlib import sha256


SYSTEM_SKILLS_ROOT = Path("internal/skills/system")
SYSTEM_SKILLS_FALLBACK_ROOT = Path("internal/skills/system")
SYSTEM_ASSETS_DEST = Path("internal/skills/system_assets.mbt")
SYSTEM_ASSETS_SALT = "v1"


def _is_hidden(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    return any(part.startswith(".") for part in rel.parts)


def _find_system_skills_root() -> Path | None:
    if SYSTEM_SKILLS_ROOT.exists() and any(SYSTEM_SKILLS_ROOT.rglob("SKILL.md")):
        return SYSTEM_SKILLS_ROOT
    if SYSTEM_SKILLS_FALLBACK_ROOT.exists() and any(
        SYSTEM_SKILLS_FALLBACK_ROOT.rglob("SKILL.md")
    ):
        return SYSTEM_SKILLS_FALLBACK_ROOT
    return None


def _collect_system_assets(root: Path) -> list[tuple[str, str]]:
    skill_dirs = sorted(
        {
            path.parent
            for path in root.rglob("SKILL.md")
            if not _is_hidden(path, root)
        }
    )
    assets: dict[str, str] = {}
    for skill_dir in skill_dirs:
        for path in skill_dir.rglob("*"):
            if not path.is_file() or _is_hidden(path, root):
                continue
            rel_path = path.relative_to(root).as_posix()
            assets[rel_path] = path.read_text(encoding="utf-8")
    return sorted(assets.items(), key=lambda item: item[0])


def _fingerprint_system_assets(assets: list[tuple[str, str]]) -> str:
    hasher = sha256()
    hasher.update(SYSTEM_ASSETS_SALT.encode("utf-8"))
    for rel_path, content in assets:
        hasher.update(rel_path.encode("utf-8"))
        hasher.update(b"\n")
        hasher.update(sha256(content.encode("utf-8")).hexdigest().encode("utf-8"))
        hasher.update(b"\n")
    return hasher.hexdigest()


def _write_system_assets_mbt(assets: list[tuple[str, str]], fingerprint: str) -> None:
    lines = [
        "///|",
        "/// Auto-generated by `scripts/embed-skills.py`. Do not edit by hand.",
        "let system_assets : Array[@assets.Asset] = [",
    ]
    for rel_path, content in assets:
        escaped_path = rel_path.replace('"', '\\"')
        lines.append("  @assets.Asset::{")
        lines.append(f'    path: "{escaped_path}",')
        lines.append("    content: (")
        for line in content.splitlines():
            lines.append(f"      #|{line}")
        lines.append("    ),")
        lines.append("  },")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append(f'let system_assets_fingerprint : String = "{fingerprint}"')
    SYSTEM_ASSETS_DEST.write_text("\n".join(lines) + "\n")
    print(f"EMBED {SYSTEM_ASSETS_DEST}")


def embed_system_skills() -> None:
    root = _find_system_skills_root()
    if root is None:
        _write_system_assets_mbt([], "empty")
        print("WARN: No system skills found to embed.")
        return
    assets = _collect_system_assets(root)
    if not assets:
        _write_system_assets_mbt([], "empty")
        print("WARN: No system skills assets found to embed.")
        return
    fingerprint = _fingerprint_system_assets(assets)
    _write_system_assets_mbt(assets, fingerprint)


if __name__ == "__main__":
    embed_system_skills()
