[project]
name = "maria-tiktoken"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.4.2",
    "tiktoken>=0.12.0",
]
